"""initial schema

Revision ID: b3491f91cc0b
Revises: 
Create Date: 2026-08-08 15:29:41.406554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3491f91cc0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preview_image', sa.String(length=2048), nullable=True),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_templates'))
    )
    op.create_index(op.f('ix_card_templates_code'), 'card_templates', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPERADMIN', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.String(length=512), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=128), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_files_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index(op.f('ix_files_owner_user_id'), 'files', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_files_sha256'), 'files', ['sha256'], unique=False)
    op.create_index(op.f('ix_files_storage_key'), 'files', ['storage_key'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('avatar_file_id', sa.String(length=36), nullable=True),
    sa.Column('logo_file_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('theme', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_file_id'], ['files.id'], name=op.f('fk_cards_avatar_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logo_file_id'], ['files.id'], name=op.f('fk_cards_logo_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['card_templates.id'], name=op.f('fk_cards_template_id_card_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards'))
    )
    op.create_index(op.f('ix_cards_avatar_file_id'), 'cards', ['avatar_file_id'], unique=False)
    op.create_index(op.f('ix_cards_logo_file_id'), 'cards', ['logo_file_id'], unique=False)
    op.create_index(op.f('ix_cards_slug'), 'cards', ['slug'], unique=True)
    op.create_index(op.f('ix_cards_template_id'), 'cards', ['template_id'], unique=False)
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_table('card_visits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('referer', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_visits_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_visits'))
    )
    op.create_index(op.f('ix_card_visits_card_id'), 'card_visits', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_visits_device_type'), 'card_visits', ['device_type'], unique=False)
    op.create_index(op.f('ix_card_visits_visited_at'), 'card_visits', ['visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_visits_visited_at'), table_name='card_visits')
    op.drop_index(op.f('ix_card_visits_device_type'), table_name='card_visits')
    op.drop_index(op.f('ix_card_visits_card_id'), table_name='card_visits')
    op.drop_table('card_visits')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_template_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_slug'), table_name='cards')
    op.drop_index(op.f('ix_cards_logo_file_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_avatar_file_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_files_storage_key'), table_name='files')
    op.drop_index(op.f('ix_files_sha256'), table_name='files')
    op.drop_index(op.f('ix_files_owner_user_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_card_templates_code'), table_name='card_templates')
    op.drop_table('card_templates')
    # ### end Alembic commands ###
